// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWXUwEZq7ikhUsvGjLWOQrbKy6fOsYuqQ',
    appId: '1:164290952174:ios:cb712ee9fb51694a9e2cff',
    messagingSenderId: '164290952174',
    projectId: 'iconica-dart-baas',
    storageBucket: 'iconica-dart-baas.firebasestorage.app',
    iosBundleId: 'com.example.todoFrontend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-K2vBlYfAdZUNRqGGj8eWzsFRYH1blVo',
    appId: '1:164290952174:web:6d3723fff38021149e2cff',
    messagingSenderId: '164290952174',
    projectId: 'iconica-dart-baas',
    authDomain: 'iconica-dart-baas.firebaseapp.com',
    storageBucket: 'iconica-dart-baas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWXUwEZq7ikhUsvGjLWOQrbKy6fOsYuqQ',
    appId: '1:164290952174:ios:cb712ee9fb51694a9e2cff',
    messagingSenderId: '164290952174',
    projectId: 'iconica-dart-baas',
    storageBucket: 'iconica-dart-baas.firebasestorage.app',
    iosBundleId: 'com.example.todoFrontend',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7EpIXj-8vGLLrpY2DmJrygLYtbGydOc',
    appId: '1:164290952174:android:d6e43eab5c56abb99e2cff',
    messagingSenderId: '164290952174',
    projectId: 'iconica-dart-baas',
    storageBucket: 'iconica-dart-baas.firebasestorage.app',
  );
}
